<br class="doNotDisplay doNotPrint" />

<!--
<div class="left"><a href="http://werc.cat-v.org/">Powered by werc</a></div>

<div class="right">
<form action="http://www.google.com/cse" id="cse-search-box" style="display: inline">
  <div style="display: inline">
    <input type="hidden" name="cx" value="partner-pub-2060328396151526:ea9sar-xttn" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q" size="32" />
    <input type="submit" name="sa" value="Search" />
  </div>
</form>
-->

<div style="margin-right: auto;"><a href="http://werc.cat-v.org">Powered by werc</a></div>

<div><form action="/_search/" method="POST"><input type="text" id="searchtext" name="q"> <input type="submit" value="Search"></form></div>
